### ISSUE TITLE
decoder exception

### ISSUE THREAD

**Issue by birdie-github** [fraunhoferhhi/vvdec#198] opened 2024-09-30 13:20 UTC
Could be a broken file but still, the decoder should exit gracefully:

```
vvdecapp --output - --y4m --bitstream vvc_frames_with_ltr.vvc
VVdeC, the Fraunhofer VVC/H.266 decoder, version 2.3.0 [THREADS=16; PARSE_DELAY=24; SIMD=AVX2]
vvdecapp [error]: decoding failed: decoder exception (decoder requires restart) detail: caught decoder exception: 
ERROR: In function "vvdec::HLSyntaxReader::parsePictureHeader(vvdec::PicHeader*, const vvdec::ParameterSetManager*, bool)::<lambda()>" in /tmp/vvdec-2.3.0/source/Lib/DecoderLib/HLSyntaxReader.cpp:3020: ph_max_mtt_hierarchy_depth_intra_slice_chroma out of bounds (read:10).
ERROR CONDITION: (ph_max_mtt_hierarchy_depth_intra_slice_chroma) < (0) || (ph_max_mtt_hierarchy_depth_intra_slice_chroma) > (std::min( 6u, CtbLog2SizeY ) - MinQtLog2SizeIntraC)

[file] Reading from stdin...
Failed to recognize file format.
Exiting... (Errors when loading file)
```

[vvc_frames_with_ltr.zip](https://github.com/user-attachments/files/17190531/vvc_frames_with_ltr.zip)

**Comment by K-os** [comment] 2024-09-30 13:50
Thanks for the report. I‘ll look into it.

What do you mean by „decoder should exit gracefully“? To me the log you posted looks like the decoder didn‘t crash but exited gracefully.

**Comment by birdie-github** [comment] 2024-09-30 14:03
> What do you mean by „decoder should exit gracefully“?

`decoding failed: decoder exception`

To me it sounds like there's some code that's failing and proper code should spit something like:

"The input stream is invalid/unsupported. Exiting".

I could be completely wrong, but in my experience "exceptions" are usually caused by critical errors in C/C++/Java code.

**Comment by K-os** [comment] 2024-09-30 14:44
The exception gets triggered by a conformance check, that ensures the fields in the picture header are within the bounds defined by the standard. If the condition of our conformance check is correct, and the problem is in your bitstream (as you suggested), everything behaves as expected.

So I will close this issue now and not investigate it any further. If you think the bitstream is correct and the decoder misbehaves, please tell me and I will reopen the issue.

**Comment by birdie-github** [comment] 2024-09-30 14:49
I found this file here:

https://chromium.googlesource.com/chromium/src/+/lkgr/media/test/data/

> vvc_frames_with_ltr.vvc
> 
> VVC stream generated manually with modified VTM to enable long term reference pictures. The stream is also encoded with multiple slices per AU, and each slice is with different reference picture lists.

It's really up to you to decide whether it's conformant or not and worth investigating into.

It's also present here: https://dl.photoprism.app/samples/Formats/Video/H.266-VVC/

**Comment by K-os** [comment] 2024-10-01 09:32
Ok, I'll look into it. The description sounds as if the stream should be ok

**Comment by MartinEesmaa** [comment] 2024-10-07 02:41
Hey guys! I got also problem too when I found out that exception error code when configuring my custom FFmpeg repo:

```
ld.lld: error: undefined symbol: std::__ndk1::basic_iostream<char, std::__ndk1::char_traits<char>>::~basic_iostream()
>>> referenced by sstream:1102 (/home/martineesmaa/mpv-android-vvc/buildscripts/sdk/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/sstream:1102)
>>>               DecLib.cpp.o:(vvdec::DecLib::create(int, int, vvdec::UserAllocator const&, vvdec::ErrHandlingFlags)) in archive /home/martineesmaa/mpv-android-vvc/buildscripts/prefix/arm64/lib/libvvdec.a
>>> referenced by sstream:1010 (/home/martineesmaa/mpv-android-vvc/buildscripts/sdk/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/sstream:1010)
>>>               vvdecimpl.cpp.o:(std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>::basic_stringstream[abi:ne180000]()) in archive /home/martineesmaa/mpv-android-vvc/buildscripts/prefix/arm64/lib/libvvdec.a
>>> referenced by sstream:1102 (/home/martineesmaa/mpv-android-vvc/buildscripts/sdk/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/sstream:1102)
>>>               vvdecimpl.cpp.o:(std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>::~basic_stringstream()) in archive /home/martineesmaa/mpv-android-vvc/buildscripts/prefix/arm64/lib/libvvdec.a

ld.lld: error: undefined symbol: std::__ndk1::basic_ios<char, std::__ndk1::char_traits<char>>::~basic_ios()
>>> referenced by sstream:1102 (/home/martineesmaa/mpv-android-vvc/buildscripts/sdk/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/sstream:1102)
>>>               DecLib.cpp.o:(vvdec::DecLib::create(int, int, vvdec::UserAllocator const&, vvdec::ErrHandlingFlags)) in archive /home/martineesmaa/mpv-android-vvc/buildscripts/prefix/arm64/lib/libvvdec.a
>>> referenced by sstream:1103 (/home/martineesmaa/mpv-android-vvc/buildscripts/sdk/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/sstream:1103)
>>>               DecLib.cpp.o:(vvdec::Exception& vvdec::Exception::operator<<<char [78]>(char const (&) [78])) in archive /home/martineesmaa/mpv-android-vvc/buildscripts/prefix/arm64/lib/libvvdec.a
>>> referenced by sstream:901 (/home/martineesmaa/mpv-android-vvc/buildscripts/sdk/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/sstream:901)
>>>               DecLib.cpp.o:(vvdec::Exception& vvdec::Exception::operator<<<char [78]>(char const (&) [78])) in archive /home/martineesmaa/mpv-android-vvc/buildscripts/prefix/arm64/lib/libvvdec.a
>>> referenced 466 more times
```

I think exception code may be problem, which may be not able to configure probably on native systems.

Feel free to ask or reply to me. Thanks! :)

- Martin Eesmaa

**Comment by adamjw24** [comment] 2024-10-07 07:38
Looks like an linking problem, see https://stackoverflow.com/questions/49183886/error-undefined-reference-to-std-ndk1localelocale

**Comment by MartinEesmaa** [comment] 2024-10-07 07:47
Hi, @adamjw24! Thank you for your response back! :)

I already tried to compile with c++_shared with `ANDROID_STL`.

So here is my CMake configuration before FFmpeg configuration:

```
cmake \
       -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI=$ndk_vvdec \
	    -DCMAKE_TOOLCHAIN_FILE=${HOME}/sdk/android-ndk-27b/build/cmake/android.toolchain.cmake \
		-DANDROID_STL=c++_shared -DVVDEC_ENABLE_LINK_TIME_OPT=OFF -DANDROID_PLATFORM=android-21 \
	    -DCMAKE_INSTALL_PREFIX=prefix ..
```

It did not work for FFmpeg configuration only, so I might need to add extra libs of libc++ or still if that persist problem exists, then I might have look something else...

Feel free to reply or ask question again to me. Thanks! :)

- Martin Eesmaa

**Comment by K-os** [comment] 2024-10-07 09:55
Can we please continue this discussion in #200 ? It's not at all helpful to mix these unrelated issues

**Comment by K-os** [comment] 2024-10-07 10:04
> [...]
> https://chromium.googlesource.com/chromium/src/+/lkgr/media/test/data/
> 
> > vvc_frames_with_ltr.vvc
> [...]

There is an actual error in the conformance check condition, and the bitstream seems to expose some other bugs in the decoder also. I'm working on fixing that and will push an update hopefully soon.

Thanks for testing VVdeC with external bitstreams with different feature combinations and for reporting your findings.

**Comment by MartinEesmaa** [comment] 2024-10-07 10:14
> Concerning the Android linking problem: Can we please continue this discussion in #200 ? It's not at all helpful to mix these unrelated issues

Sorry about that, @K-os. I apologize with that I did not create issue. I thought it's like similar exception to error library code :/.

Thanks for creating an issue of my comment at #200! :)

- Martin Eesmaa

**Comment by adamjw24** [comment] 2024-10-11 10:09
> [vvc_frames_with_ltr.zip](https://github.com/user-attachments/files/17190531/vvc_frames_with_ltr.zip)

Amazing bitstream. The best conformance file I have to date. Thanks for posting.

**Closed** 2024-10-11 10:12 UTC
