### ISSUE TITLE
https://github.com/fraunhoferhhi/vvdec

### ISSUE THREAD

**Issue by yurivict** [fraunhoferhhi/vvdec#170] opened 2024-03-13 17:45 UTC
```
In file included from /usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:43:
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/./vvdecimpl.h:228:14: error: cast from pointer to smaller type 'TRet' (aka 'int') loses information
      return (TRet) NULL;
             ^~~~~~~~~~~
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:205:21: note: in instantiation of function template specialization 'vvdec::VVDecImpl::catchExceptions<int (vvdec::VVDecImpl::*)(const vvdecParams &, void *(*)(void *, vvdecComponentType, unsigned int, unsigned int, void **), void (*)(void *, void *)), vvdecParams, std::nullptr_t, std::nullptr_t>' requested here
  int ret = decCtx->catchExceptions( &vvdec::VVDecImpl::init, *params, nullptr, nullptr );
                    ^
In file included from /usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:43:
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/./vvdecimpl.h:228:14: error: cast from pointer to smaller type 'TRet' (aka 'int') loses information
      return (TRet) NULL;
             ^~~~~~~~~~~
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:247:21: note: in instantiation of function template specialization 'vvdec::VVDecImpl::catchExceptions<int (vvdec::VVDecImpl::*)(const vvdecParams &, void *(*)(void *, vvdecComponentType, unsigned int, unsigned int, void **), void (*)(void *, void *)), vvdecParams, void *(*)(void *, vvdecComponentType, unsigned int, unsigned int, void **), void (*)(void *, void *)>' requested here
  int ret = decCtx->catchExceptions( &vvdec::VVDecImpl::init, *params, callbackBufAlloc, callbackBufUnref );
                    ^
In file included from /usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:43:
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/./vvdecimpl.h:228:14: error: cast from pointer to smaller type 'TRet' (aka 'int') loses information
      return (TRet) NULL;
             ^~~~~~~~~~~
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:271:22: note: in instantiation of function template specialization 'vvdec::VVDecImpl::catchExceptions<int (vvdec::VVDecImpl::*)()>' requested here
  const int ret = d->catchExceptions( &vvdec::VVDecImpl::uninit );
                     ^
In file included from /usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:43:
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/./vvdecimpl.h:228:14: error: cast from pointer to smaller type 'TRet' (aka 'int') loses information
      return (TRet) NULL;
             ^~~~~~~~~~~
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:306:13: note: in instantiation of function template specialization 'vvdec::VVDecImpl::catchExceptions<int (vvdec::VVDecImpl::*)(vvdecAccessUnit &, vvdecFrame **), vvdecAccessUnit, vvdecFrame **>' requested here
  return d->catchExceptions( &vvdec::VVDecImpl::decode, *accessUnit, frame );
            ^
In file included from /usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:43:
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/./vvdecimpl.h:228:14: error: cast from pointer to smaller type 'TRet' (aka 'int') loses information
      return (TRet) NULL;
             ^~~~~~~~~~~
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:320:13: note: in instantiation of function template specialization 'vvdec::VVDecImpl::catchExceptions<int (vvdec::VVDecImpl::*)(vvdecFrame **), vvdecFrame **>' requested here
  return d->catchExceptions( &vvdec::VVDecImpl::flush, frame );
            ^
In file included from /usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/vvdec.cpp:43:
/usr/ports/multimedia/vvdec/work/vvdec-2.2.0/source/Lib/vvdec/./vvdecimpl.h:228:14: error: cast from pointer to smaller type 'TRet' (aka 'int') loses information
      return (TRet) NULL;
             ^~~~~~~~~~~
```

NULL isn't generally defined as zero, instead it is defined as nullptr.

You need to use "0" in these places.

Version: 2.2.0
clang-16
FreeBSD 14.0

**Comment by K-os** [comment] 2024-03-15 14:57
Hi!
thanks for the report. I fixed the issue as you suggested in [branch fix_gh170_freebsd_clang16_build in my fork](https://github.com/K-os/vvdec/tree/fix_gh170_freebsd_clang16_build). Can you please verify that the issue is fixed now?
I don't have a FreeBSD machine to test it and the clang-16 & 17 versions for debian/ubuntu, that I tried, did not show the issue.

**Closed** 2024-03-26 09:03 UTC
